version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  build:
    commands:
      - echo "Building Docker image with multi-stage build..."
      - docker build -t $ImageName .

  post_build:
    commands:
      - echo Build completed on `date`
      - docker images

artifacts:
  files:
    - back-end/Dockerrun.aws.json
  name: containerapp-artifacts