version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo Build started on `date`
      - java -version
      - mvn --version

  build:
    commands:
      - cd back-end

      # Maven build no CodeBuild (sem Docker)
      - chmod +x mvnw
      - ./mvnw clean package -DskipTests

      # Docker build apenas com runtime
      - echo "Building Docker image with pre-compiled JAR..."
      - docker build -t containerapp:$CODEBUILD_BUILD_NUMBER .
      - docker tag containerapp:$CODEBUILD_BUILD_NUMBER containerapp:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - docker images

artifacts:
  files:
    - back-end/Dockerrun.aws.json
    - back-end/target/containerView-*.jar
  name: containerapp-artifacts

cache:
  paths:
    - '/root/.m2/**/*'